mod variable_bindings;
mod functions;
mod primitive_types;
mod if_examples;
mod loops;
mod vectors;
mod ownership;
mod references_and_borrowing;
mod lifetimes;
mod mutability;
mod structs;
mod enums;
mod matching;
mod patterns;
mod method_syntax;
mod strings;
mod generics;
mod traits;
mod drop;
mod if_let_while_let;
mod trait_objects;
mod closures;
mod universal_function_call_syntax;
mod const_and_static;
mod attributes;
mod type_aliases;
mod coercion;
mod associated_types;
mod unsized_types;

pub use self::variable_bindings::*;
pub use self::functions::*;
pub use self::primitive_types::*;
pub use self::if_examples::*;
pub use self::loops::*;
pub use self::vectors::*;
pub use self::ownership::*;
pub use self::references_and_borrowing::*;
pub use self::lifetimes::*;
pub use self::mutability::*;
pub use self::structs::*;
pub use self::enums::*;
pub use self::matching::*;
pub use self::patterns::*;
pub use self::method_syntax::*;
pub use self::strings::*;
pub use self::generics::*;
pub use self::traits::*;
pub use self::drop::*;
pub use self::if_let_while_let::*;
pub use self::trait_objects::*;
pub use self::closures::*;
pub use self::universal_function_call_syntax::*;
pub use self::const_and_static::*;
pub use self::attributes::*;
pub use self::type_aliases::*;
pub use self::coercion::*;
pub use self::associated_types::*;
pub use self::unsized_types::*;
